//TYPES RELATED TO Dashboard Layout

export const SET_LAYOUT = 'SET_LAYOUT';

export const TOGGLE_SCROLL_ENABLED = 'TOGGLE_SCROLL_ENABLED'

export const TOGGLE_IS_LOADING = 'SET_IS_LOADING';


//TYPES RELATED TO USER ACTION

export const UPDATE_USER = 'UPDATE_USER';

export const SET_USER_INFO = 'SET_USER_INFO';

export const SET_USER_EMAIL = 'SET_USER_EMAIL';

export const SET_USER_PASS = 'SET_USER_PASS';

//TYPES RELATED TO DASHBOARD

export const TOGGLE_TRASH = 'TOGGLE_TRASH';

export const UPDATE_TOOLBAR_ICON = 'UPDATE_TOOLBAR_ICON';

export const DELETE_TOOLBAR_ICON = 'DELETE_TOOLBAR_ICON';

export const SWITCH_TOOLBAR_ICONS = 'SWITCH_TOOLBAR_ICONS';

export const SET_SEARCH_MARKER = 'SET_SEARCH_MARKER';

export const SET_NEW_ICON = 'SET_NEW_ICON';

export const CLEAR_NEW_ICON = 'CLEAR_NEW_ICON';

export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';

export const TOGGLE_PLUS = 'TOGGLE_PLUS';

